### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by Angus771**
needed information to log in...

### CODE REVIEW

**Comment by mudler** [comment]
Sorry, didn't noticed it before. Care to rebase? (even if at the moment of writing, autologin should work on the desktop ISOs)

**Comment by Angus771** [comment]
Will download an iso today, try and inform you

**Comment by Angus771** [comment]
Tried the latest GNOME ISO, login was as predicted automatically. Worked flawlessly! 🙂

**Comment by mudler** [comment]
Closing then, thank you!

**Pull request closed without merging**
